README: Add 'Getting started' directions
flatpak/libportal pull request #43
Opened 2021-06-21 17:10 UTC by cassidyjames

Based on #29, but a bit expanded and hopefully addressing concerns on that PR. Omits docs instructions for now as I'm not familiar with how that works.

2021-06-21 17:37 UTC, cassidyjames commented
I would like to add a section like this at the end, but am unable to actually build the docs locally for some reason, so I'm omitting for now:

>### Docs
>
>libportal can optionally generates docs with the `gtk_doc` option which defaults to `true`. View the resulting documentation in the `doc/html/` subdirectory of your build directory, e.g.:
>
>```
>gio open _build/doc/html/index.html
>```

2021-07-28 14:37 UTC, GeorgesStavracas requested changes
Mostly looks good, clearly an improvement over the single sentence we currently have, but could you please limit the line width to 80 characters?

2021-07-28 15:55 UTC, GeorgesStavracas requested changes
Okay, sorry I didn't catch this in the previous round. I think it's good to land after these adjustments.

2021-07-28 15:55 UTC, GeorgesStavracas commented on README.md
> +the project to compile the corresponding binary. Then run the binary, e.g.:
This was recently changed to `portal-tests`, and it is passed as `-Dportal-tests=gtk3,gtk4,qt` (or any combination, or none to disable all tests)

2021-07-28 15:55 UTC, GeorgesStavracas commented on README.md
> +./_build/portal-test/portal-test
And correspondingly to the previous comment, the file paths changed to e.g. `portal-test/gtk3/portal-test-gtk3`

2021-07-28 15:55 UTC, GeorgesStavracas commented on README.md
> +meson configure _build -Dbuild-portal-test=true
See previous comments; it's now `-Dportal-tests=...`

2021-07-28 16:24 UTC, GeorgesStavracas approved these changes
Thank you so much!

2021-07-28 16:24 UTC, merged